server:
  port: 8111
spring:
  application:
    name: item-server
  datasource:
    url: jdbc:mysql://rm-uf66k9xg41auipoku.mysql.rds.aliyuncs.com/warshop?serverTimezone=Asia/Shanghai
    username: root
    password: 33559874Asen-
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true